### ISSUE TITLE
Paths are confused

### ISSUE THREAD

**Issue by kevin201** [parthp1808/Laravel-todo-app#1]
Installed using xampp in a subdirectory. Using 'localhost/subdir' I get a directory list. Using 'localhost/subdir/public' I get the welcome page, but then continuing errors because the links are going to the top level 'localhost/login, tasks, edit etc.' .env includes APP_URL=http://localhost/subdir. How to correct at an application level?

**Comment by parthp1808** [comment]
Since you are using xampp and not laravel serve, you need to use apache .htaccess file for redirection setup. 
Check this - https://laravel.com/docs/6.x/installation#pretty-urls

**Comment by kevin201** [comment]
Hi, thanks, I will give that a go. Still learning!

**Comment by kevin201** [comment]
No, still the same. Works fine with php artisan serve, but can't get it to work using XAMPP

**Comment by ritechoice23** [comment]
i am also having the same issue

**Comment by parthp1808** [comment]
> i am also having the same issue

@kevin201 @horlatech2020
Did you try using Apache redirects?
- locally it's better to use `php artisan server` or use [Laravel Homestead](https://laravel.com/docs/7.x/homestead)
- it's trickier and more hassle to configure laravel locally in subfolders ~ not worth it at all imo

Here's one solution you can try - https://medium.com/@umaams/multiple-laravel-sites-on-sub-directory-using-apache-webserver-91fa20e57ac4

Let me know your progress.
P.S - I haven't tried this article's solution personally yet.

**Comment by ritechoice23** [comment]
Ok
